# Generated by Django 5.0.1 on 2024-01-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('review_score', models.FloatField(default=0)),
                ('years', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=False, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
